spring:
  application:
    name: laundry-pos-backend

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:laundry_pos}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:9113624230}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:8080}
  error:
    include-message: always

app:
  jwt:
    secret: ${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS1mb3ItbGF1bmRyeS1wb3MtMjAyNi0xMjM0NTY=}
    expiration-ms: 86400000

whatsapp:
  api-url: https://graph.facebook.com/v25.0
  phone-number-id: 1247146801821169
  business-account-id: 2478197572681762
  access-token: EAAfpFZAkGN0sBSLPdyFLuiUryUHLrQnGypMMuycvgNrZCFebNE8em2HrMgqGT5hzABKE2mExpJhrSkZAzZCygthPXlZBwbQkqGYQ9vgNTczRwhHZA5p8oZCcbZAZAO4NpuQMSzZCGmMqO9rKT2C9oGlQlb7A0rnKe6ZBHZBrmT9OUmZAEYTFuGWCV6MULsHKQs5HfmZAvZBzrH6S9ZBASHt0XmW7g81SnfKNNJpVJ96c4iLFmO3tO4YeFlZCW3EqQ6r0zGX7FSPuRFaPrS30twjyjq5ZCM