spring:
  application:
    name: laundry-pos-backend

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:laundry_pos}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:9113624230 }

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:8080}

  error:
    include-message: always

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000